apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world
spec:
  selector:
    matchLabels:
      name: hello-world
  template:
    metadata:
      labels:
    spec:
      securityContext:
#        runAsUser: 1000
#        runAsGroup: 3000
#        fsGroup: 2000
      containers:
      - name: nginx
        image: nginx
        resources:
         requests:
           cpu: 10m
           memory: 64Mi
        securityContext:
#          allowPrivilegeEscalation: false 
          capabilities:
            drop:
            - ALL
