apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: hello-world
    environment: lab
    name: hello-world
  name: hello-world
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: hello-world
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    name: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
    environment: lab
    name: hello-world
  name: hello-world
  namespace: hello-world
spec:
  selector:
    matchLabels:
      name: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        environment: lab
        name: hello-world
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: hello-world
  namespace: hello-world
spec:
  ingressClassName: nginx
  rules:
  - host: hello-world.info
    http:
      paths:
      - backend:
          service:
            name: hello-world
            port:
              number: 8080
        path: /
        pathType: Prefix
